# Generated by Django 4.2.14 on 2024-07-13 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("songnapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="songnapp.song",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="songnapp.album",
            ),
        ),
    ]
