# Generated by Django 4.2.14 on 2024-07-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songnapp", "0002_alter_review_song_alter_song_album"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="review", new_name="content",
        ),
    ]
